### ISSUE TITLE
Division by zero error

### ISSUE THREAD

**Issue by serbulent** [hkmztrk/SMILESVecProteinRepresentation#1]
When I try to get vectors of human proteins using;

` python getligprotvec.py drug.pubchem.canon.l8.ws20.txt`

or 

`python getligprotvec.py drug.l8.chembl23.canon.ws20.txt `

I got error as;

```
('Fetching interactions for', 'Q9HAV4', 'none')
Traceback (most recent call last):
  File "getligprotvec.py", line 103, in <module>
    getProteinVec(proteins_path)
  File "getligprotvec.py", line 94, in getProteinVec
    sumVec = [sumVec[i]/len(ligands) for i in range(len(sumVec))]
ZeroDivisionError: float division by zero
```

If you need any further info I can happy to supply it.

**Comment by hkmztrk** [comment]
@serbulent thanks a lot for your interest in our work!

It seems the system couldn't find any interacting ligands for Q9HAV4, but I can't say for sure.
Yes, It'd be super helpful if you provide more information or the data you are working on.
Best!

**Comment by serbulent** [comment]
Thanks for your attention!

You can see the prots_sample.txt file from this link;

https://drive.google.com/open?id=1z8YBmMTjPWDiTU6yr8LtQIkUHxVI_y5g

I hope this is enough for you to repeat the error, please inform me if any other specific information is needed.

**Comment by hkmztrk** [comment]
Thank you for the file! I'll try to get back to you in a few days!

**Comment by hkmztrk** [comment]
Hello @serbulent, I was away from my computer for a while, now I finally found a time to run the code with your data. Thanks for your patience.

**Comment by hkmztrk** [comment]
Hello @serbulent, I updated the code so that the system will not produce an error in case of no interacting ligand is found. Thanks for pointing the error out!

Could you please check this new version and verify it's working?

**Comment by serbulent** [comment]
Thank you it seem solved. But now I have new error. If connection lost during process it stops and I have to restart it. I it possible to us a parameter such as --max_try to solve this ? Or I can open a new issue for this ?

PS: The error message is below;

('Fetching interactions for', 'P63092', 'CHEMBL4377')
Traceback (most recent call last):
  File "getligprotvec.py", line 104, in <module>
    getProteinVec(proteins_path)
  File "getligprotvec.py", line 78, in getProteinVec
    PLIlist = getLigandInteractions(proteins_path)
  File "getligprotvec.py", line 63, in getLigandInteractions
    compounds = activity_parser(activities)
  File "getligprotvec.py", line 38, in activity_parser
    for activity in activities:
  File "/home/srb/.local/lib/python2.7/site-packages/chembl_webresource_client/query_set.py", line 116, in next
    self.chunk = self.query.next_page()
  File "/home/srb/.local/lib/python2.7/site-packages/chembl_webresource_client/url_query.py", line 435, in next_page
    return self.get_page()
  File "/home/srb/.local/lib/python2.7/site-packages/chembl_webresource_client/url_query.py", line 390, in get_page
    res = session.post(self.base_url + '.' + self.frmt, json=data, timeout=self.timeout)
  File "/home/srb/.local/lib/python2.7/site-packages/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/srb/.local/lib/python2.7/site-packages/requests_cache/core.py", line 132, in request
    **kwargs
  File "/home/srb/.local/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/srb/.local/lib/python2.7/site-packages/requests_cache/core.py", line 105, in send
    return send_request_and_cache_response()
  File "/home/srb/.local/lib/python2.7/site-packages/requests_cache/core.py", line 97, in send_request_and_cache_response
    response = super(CachedSession, self).send(request, **kwargs)
  File "/home/srb/.local/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/srb/.local/lib/python2.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))

**Comment by hkmztrk** [comment]
Hello @serbulent, thanks for the feedback!
Could you open a new issue? It'd be better to track, I guess.
