### ISSUE TITLE
Pickle object error in Python3

### ISSUE THREAD

**Issue by serbulent** [hkmztrk/SMILESVecProteinRepresentation#3]
The created protein vector can be opened with python2 but can not be opened with python3.

```
>>> import pickle
>>> pickle.load(open("protein.vec"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: a bytes-like object is required, not 'str'
```

**Comment by hkmztrk** [comment]
@serbulent, could you try it with: 

`pickle.load(open("protein.vec"), encoding='latin1')  `

**Comment by serbulent** [comment]
Still same error :(

```
Python 3.6.8 (default, Jan 14 2019, 11:02:34) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pickle
>>> pickle.load(open("protein.vec"), encoding='latin1')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: a bytes-like object is required, not 'str'
```

**Comment by hkmztrk** [comment]
It is interesting because if you are working on Python3.x pickle dump should also be endoded that way, since it is generated on the fly.  How about this?

```
with open('protein.vec', 'rb') as f:
        prots= pickle.load(f, encoding='bytes')
```

**Comment by serbulent** [comment]
It works with encoding='bytes' thanks. May be it is good to update it on readme.md :)
